/* autogenerated from "macros/Misc/DEADBAND.sci" */
function DEADBAND() {
DEADBAND.prototype.define = function DEADBAND() {
minp=-.5;
maxp=.5;
rpar=[maxp,minp];
model=scicos_model();
model.sim=list("deadband",4);
model.in1=1;
model.nzcross=2;
model.nmode=1;
model.out=1;
model.rpar=rpar;
model.blocktype="c";
model.dep_ut=[true,false];
exprs=[string(maxp),string(minp),string(model.nmode)];
gr_i=[];
x=standard_define([2,2],model,exprs,gr_i);
}
DEADBAND.prototype.details = function DEADBAND() {
}
DEADBAND.prototype.get = function DEADBAND() {
}
DEADBAND.prototype.set = function DEADBAND() {
x=arg1;
graphics=arg1.graphics;
exprs=graphics.exprs;
model=arg1.model;
while (true) {
[ok,maxp,minp,zeroc,exprs]=scicos_getvalue("Set Deadband parameters",["End of dead band","Start of dead band","zero crossing (0:no, 1:yes)"],list("vec",1,"vec",1,"vec",1),exprs);
if (!ok) {
break;
}
if (maxp<=minp) {
message("Upper limit must be > Lower limit");
} else {
rpar=[maxp,minp];
model.rpar=rpar;
if (zeroc!=0) {
model.nzcross=2;
model.nmode=1;
} else {
model.nzcross=0;
model.nmode=0;
}
graphics.exprs=exprs;
x.graphics=graphics;
x.model=model;
break;
}
}
}
}
