Syntax error in input LexToken(SCICOS_DIAGRAM,'scicos_diagram',1,4093)
Syntax error in input LexToken(VAR,'blk',1,4450)
Syntax error in input LexToken(VAR,'blk',1,4827)
Syntax error in input LexToken(VAR,'blk',1,5266)
Syntax error in input LexToken(VAR,'blk',1,5620)
Syntax error in input LexToken(VAR,'lnk',1,5987)
Syntax error in input LexToken(VAR,'lnk',1,6141)
Syntax error in input LexToken(VAR,'lnk',1,6293)
/* autogenerated from "macros/Misc/EDGE_TRIGGER.sci" */
None
