/* autogenerated from "macros/Misc/Extract_Activation.sci" */
function Extract_Activation() {
    Extract_Activation.prototype.define = function Extract_Activation() {
        var scs_m_1 = scicos_diagram();
        scs_m_1.objs[1-1] = IFTHEL_f("define");
        scs_m_1.objs[2-1] = CLKSOMV_f("define");
        scs_m_1.objs[3-1] = IN_f("define");
        scs_m_1.objs[4-1] = CLKOUTV_f("define");
        scs_m_1.objs[5-1] = scicos_link();
        scs_m_1.objs[6-1] = scicos_link();
        scs_m_1.objs[7-1] = scicos_link();
        scs_m_1.objs[8-1] = scicos_link();
        var blk = scs_m_1.objs[1-1];
        var graphics = blk.graphics;
        this.model = blk.model;
        graphics.orig = [80,0];
        graphics.sz = [60,40];
        graphics.exprs = [["0"],["0"]];
        this.model.evtin = new ScilabDouble([]);
        this.model.nzcross = new ScilabDouble([0]);
        this.model.nmode = new ScilabDouble([0]);
        graphics.pin = 7;
        graphics.peout = [[5],[6]];
        blk.graphics = graphics;
        blk.model = this.model;
        scs_m_1.objs[1-1] = blk;
        var blk = scs_m_1.objs[2-1];
        var graphics = blk.graphics;
        this.model = blk.model;
        graphics.orig = [80,-80];
        graphics.sz = [80,40];
        graphics.pein = [[5],[6]];
        graphics.peout = 8;
        blk.graphics = graphics;
        blk.model = this.model;
        scs_m_1.objs[2-1] = blk;
        var blk = scs_m_1.objs[3-1];
        var graphics = blk.graphics;
        this.model = blk.model;
        graphics.orig = [0,10];
        graphics.sz = [20,20];
        graphics.exprs = ["1"];
        this.model.ipar = new ScilabDouble([1]);
        graphics.pout = 7;
        blk.graphics = graphics;
        blk.model = this.model;
        scs_m_1.objs[3-1] = blk;
        var blk = scs_m_1.objs[4-1];
        var graphics = blk.graphics;
        this.model = blk.model;
        graphics.orig = [110,-140];
        graphics.sz = [20,20];
        graphics.exprs = ["1"];
        this.model.ipar = new ScilabDouble([1]);
        graphics.pein = 8;
        blk.graphics = graphics;
        blk.model = this.model;
        scs_m_1.objs[4-1] = blk;
        var lnk = scs_m_1.objs[5-1];
        lnk.ct = [5,-1];
        lnk.from = [1,1,0];
        lnk.to = [2,1,1];
        scs_m_1.objs[5-1] = lnk;
        var lnk = scs_m_1.objs[6-1];
        lnk.ct = [5,-1];
        lnk.from = [1,2,0];
        lnk.to = [2,2,1];
        scs_m_1.objs[6-1] = lnk;
        var lnk = scs_m_1.objs[7-1];
        lnk.from = [3,1,0];
        lnk.to = [1,1,1];
        scs_m_1.objs[7-1] = lnk;
        var lnk = scs_m_1.objs[8-1];
        lnk.ct = [5,-1];
        lnk.from = [2,1,0];
        lnk.to = [4,1,1];
        scs_m_1.objs[8-1] = lnk;
        blk={};
        lnk={};
        this.model = scicos_model();
        this.model.sim = new ScilabString(["csuper"]);
        this.model.in1 = new ScilabDouble([1]);
        this.model.evtout = new ScilabDouble([1]);
        this.model.rpar = scs_m_1;
        var gr_i = [];
        this.x = standard_define([3,2],this.model,[],gr_i);
        return new BasicBlock(this.x);
    }
    Extract_Activation.prototype.details = function Extract_Activation() {
        return this.x;
    }
    Extract_Activation.prototype.get = function Extract_Activation() {
        var options = {
        }
        return options;
    }
    Extract_Activation.prototype.set = function Extract_Activation() {
        this.x = arg1;
        return new BasicBlock(this.x);
    }
}
