/* autogenerated from "macros/NonLinear/LOOKUP_f.sci" */
function LOOKUP_f() {
LOOKUP_f.prototype.define = function LOOKUP_f() {
model=scicos_model();
model.sim="lookup";
model.in1=1;
model.out=1;
model.rpar=[-2,-1,1,2,-1,1,-1,1];
model.blocktype="c";
model.dep_ut=[true,false];
gr_i=[];
x=standard_define([2,2],model,[],gr_i);
}
LOOKUP_f.prototype.details = function LOOKUP_f() {
}
LOOKUP_f.prototype.get = function LOOKUP_f() {
}
LOOKUP_f.prototype.set = function LOOKUP_f() {
x=arg1;
graphics=arg1.graphics;
exprs=graphics.exprs;
model=arg1.model;
rpar=model.rpar;
n=size(rpar,"*")/2;
xx=rpar.slice(1-1,n);
yy=rpar.slice(n+1-1,2*n);
while (true) {
[ln,fun]=where()
if (!or(fun=="do_eval")) {
[xx,yy,ok,gc]=edit_curv(xx,yy,"axy");
} else {
ok=true;
}
if (!ok) {
break
}
n=size(xx,"*");
if (or(xx.slice(2-1,n)-xx.slice(1-1,n-1)<=0)) {
message("You have not defined a function");
ok=false;
}
if (ok) {
model.rpar=[xx.slice(),yy.slice()];
x.graphics=graphics;
x.model=model;
break
}
}
}
}
