/* autogenerated from "macros/NonLinear/MIN_f.sci" */
function MIN_f() {
    MIN_f.prototype.define = function MIN_f() {
        in1 = -1;
        this.model = scicos_model();
        this.model.sim = new ScilabString("minblk");
        this.model.in1 = new ScilabDouble(in1);
        this.model.out = new ScilabDouble(1);
        this.model.dstate = [[0],[0]];
        this.model.blocktype = new ScilabString("c");
        this.model.dep_ut = [true,false];
        exprs = sci2exp(in1);
        gr_i = [];
        this.x = standard_define([2,2],this.model,exprs,gr_i);
        return new BasicBlock(this.x);
    }
    MIN_f.prototype.details = function MIN_f() {
        return this.x;
    }
    MIN_f.prototype.get = function MIN_f() {
        var options = {
        }
        return options;
    }
    MIN_f.prototype.set = function MIN_f() {
        this.x = arg1;
        return new BasicBlock(this.x);
    }
}
