/* autogenerated from "macros/NonLinear/SINBLK_f.sci" */
function SINBLK_f() {
    SINBLK_f.prototype.define = function SINBLK_f() {
model=scicos_model();
model.sim="sinblk";
model.in1=-1;
model.out=-1;
model.blocktype="c";
model.dep_ut=[true,false];
exprs=" ";
gr_i=[];
x=standard_define([2,2],model,exprs,gr_i);
    }
    SINBLK_f.prototype.details = function SINBLK_f() {
    }
    SINBLK_f.prototype.get = function SINBLK_f() {
    }
    SINBLK_f.prototype.set = function SINBLK_f() {
x=arg1;
    }
}
