/* autogenerated from "macros/NonLinear/TANBLK_f.sci" */
function TANBLK_f() {
    TANBLK_f.prototype.define = function TANBLK_f() {
        in1 = -1;
        model = scicos_model();
        model.sim = "tanblk";
        model.in1 = in1;
        model.out = in1;
        model.blocktype = "c";
        model.dep_ut = [true,false];
        exprs = sci2exp(in1);
        gr_i = [];
        this.x = standard_define([2,2],model,exprs,gr_i);
    }
    TANBLK_f.prototype.details = function TANBLK_f() {
        return this.x;
    }
    TANBLK_f.prototype.get = function TANBLK_f() {
    }
    TANBLK_f.prototype.set = function TANBLK_f() {
        this.x = arg1;
        this.x.model.firing = [];
    }
}
