/* autogenerated from "macros/NonLinear/TrigFun.sci" */
function TrigFun() {
    TrigFun.prototype.define = function TrigFun() {
        this.model = scicos_model();
        this.model.sim = list(new ScilabString(["sin_blk"]), new ScilabDouble([4]));
        this.model.in = new ScilabDouble([-1]);
        this.model.out = new ScilabDouble([-1]);
        this.model.blocktype = new ScilabString(["c"]);
        this.model.dep_ut = new ScilabDouble([true,false]);
        this.exprs = "sin";
        this.gr_i = new ScilabString(["xstringb(orig(1),orig(2),\"TrigFun\",sz(1),sz(2));"]);
        this.x = standard_define([4,2],this.model,this.exprs,this.gr_i);
        return new BasicBlock(this.x);
    }
    TrigFun.prototype.details = function TrigFun() {
        return this.x;
    }
    TrigFun.prototype.get = function TrigFun() {
        var options = {
        }
        return options;
    }
    TrigFun.prototype.set = function TrigFun() {
        this.fun = arguments[0]["fun"]
        this.exprs = arguments[0]["exprs"]
        this.exprs = this.graphics.exprs;
        var PREVAR_FF = [["sin"],["cos"],["tan"],["asin"],["acos"],["atan"],["sinh"],["cosh"],["tanh"],["asinh"],["acosh"],["atanh"]];
        var PREVAR_GG = [["Choose among "+strcat(PREVAR_FF.slice(1-1,4),", ")],[strcat(PREVAR_FF.slice(5-1,$),", ")]];
        while (true) {
            [ok,this.fun,this.exprs] = scicos_getvalue(PREVAR_GG,"Function",list("str",1),this.exprs);
            if (!ok) {
                break;
            }
            if (find(PREVAR_FF==this.fun)==[]) {
                message("Sorry but "+this.fun+" is not in the list!");
            } else {
                this.graphics.exprs = new ScilabDouble([this.exprs]);
                execstr("model.sim=list(\'"+this.fun+"_blk\',4)");
                this.x.graphics = this.graphics;
                this.x.model = this.model;
                break;
            }
        }
        return new BasicBlock(this.x);
    }
}
