/* autogenerated from "macros/Branching/CLKFROM.sci" */
function CLKFROM() {
CLKFROM.prototype.get = function CLKFROM() {
}
CLKFROM.prototype.set = function CLKFROM() {
x=arg1;
graphics=arg1.graphics;
model=arg1.model;
exprs=graphics.exprs;
while (true) {
[ok,tag,exprs]=scicos_getvalue("Set block parameters","Tag",list("str",-1),exprs);
if (!ok) {
break
}
if (model.opar!=list(tag)) {
needcompile=4;
y=needcompile;
}
model.opar=list(tag);
model.evtout=1;
model.firing=-1;
graphics.exprs=exprs;
x.graphics=graphics;
x.model=model;
break
}
needcompile=resume(needcompile)
}
CLKFROM.prototype.define = function CLKFROM() {
model=scicos_model();
model.sim="clkfrom";
model.evtout=1;
model.opar=list("A");
model.blocktype="d";
model.firing=-1;
model.dep_ut=[false,false];
exprs="A";
x=standard_define([2,1],model,exprs," ");
x.graphics.id="From";
}
CLKFROM.prototype.details = function CLKFROM() {
}
}
