/* autogenerated from "macros/Electrical/VariableResistor.sci" */
function VariableResistor() {
    VariableResistor.prototype.define = function VariableResistor() {
        this.model = scicos_model();
        this.model.sim = new ScilabString(["VariableResistor"]);
        this.model.blocktype = new ScilabString(["c"]);
        this.model.dep_ut = new ScilabBoolean([true,false]);
        var mo = modelica();
        mo.model = "VariableResistor";
        mo.inputs = ["p","R"];
        mo.outputs = "n";
        this.model.equations = new ScilabDouble([mo]);
        this.model.in = new ScilabDouble([ones(size(mo.inputs,"*"),1)]);
        this.model.out = new ScilabDouble([ones(size(mo.outputs,"*"),1)]);
        var exprs = [];
        var gr_i = new ScilabString(["xstringb(orig(1),orig(2),\"VariableResistor\",sz(1),sz(2));"]);
        this.x = new standard_define(new ScilabDouble([2,2]),this.model,new ScilabDouble(exprs),list(gr_i,0));
        this.x.graphics.in_implicit = ["I","E"];
        this.x.graphics.out_implicit = ["I"];
        return new BasicBlock(this.x);
    }
    VariableResistor.prototype.details = function VariableResistor() {
        return this.x;
    }
    VariableResistor.prototype.get = function VariableResistor() {
        alert("parameters cannot be modified");
    }
    VariableResistor.prototype.set = function VariableResistor() {
        return new BasicBlock(this.x);
    }
    VariableResistor.prototype.get_popup_title = function VariableResistor() {
        var set_param_popup_title = "Set parameters";
        return set_param_popup_title;
    }
}
