/* autogenerated from "macros/Events/CLKSOMV_f.sci" */
function CLKSOMV_f() {
    CLKSOMV_f.prototype.define = function CLKSOMV_f() {
        this.model = scicos_model();
        this.model.sim = new ScilabString(["sum"]);
        this.model.evtin = new ScilabDouble([1],[1],[1]);
        this.model.evtout = new ScilabDouble([1]);
        this.model.blocktype = new ScilabString(["d"]);
        this.model.firing = new ScilabDouble([-1]);
        this.model.dep_ut = new ScilabBoolean([false,false]);
        var gr_i = new ScilabString(["xstringb(orig(1),orig(2),\"CLKSOMV_f\",sz(1),sz(2));"]);
        this.x = new standard_define(new ScilabDouble([2,2]),this.model,new ScilabDouble([]),gr_i);
        return new RoundBlock(this.x);
    }
    CLKSOMV_f.prototype.details = function CLKSOMV_f() {
        return this.x;
    }
    CLKSOMV_f.prototype.get = function CLKSOMV_f() {
        alert("parameters cannot be modified");
    }
    CLKSOMV_f.prototype.set = function CLKSOMV_f() {
        return new RoundBlock(this.x);
    }
}
