/* autogenerated from "macros/Events/CLKSOMV_f.sci" */
function CLKSOMV_f() {
CLKSOMV_f.prototype.get = function CLKSOMV_f() {
}
CLKSOMV_f.prototype.set = function CLKSOMV_f() {
x=arg1;
}
CLKSOMV_f.prototype.define = function CLKSOMV_f() {
model=scicos_model();
model.sim="sum";
model.evtin=[1,1,1];
model.evtout=1;
model.blocktype="d";
model.firing=-1;
model.dep_ut=[None,None];
gr_i=[];
x=standard_define([2,2],model,[],gr_i);
}
CLKSOMV_f.prototype.details = function CLKSOMV_f() {
}
}
