/* autogenerated from "macros/Events/EVTDLY_c.sci" */
function EVTDLY_c() {
    EVTDLY_c.prototype.define = function EVTDLY_c() {
        this.dt = 0.1;
        this.ff = 0.0;
        model = scicos_model();
        model.sim = list("evtdly4",4);
        model.evtin = 1;
        model.evtout = 1;
        model.rpar = [[this.dt],[this.ff]];
        model.blocktype = "d";
        model.firing = this.ff;
        model.dep_ut = [false,false];
        exprs = [[string(this.dt)],[sci2exp(this.ff)]];
        gr_i = [];
        this.x = standard_define([3,2],model,exprs,gr_i);
        return new BasicBlock(this.x);
    }
    EVTDLY_c.prototype.details = function EVTDLY_c() {
        return this.x;
    }
    EVTDLY_c.prototype.get = function EVTDLY_c() {
        var options = {
            dt:["Delay",this.dt],
            ff:["Date of initial output event",this.ff],
        }
        return options;
    }
    EVTDLY_c.prototype.set = function EVTDLY_c() {
        this.dt = parseFloat(arguments[0]["dt"])
        this.ff = parseFloat(arguments[0]["ff"])
        this.x = arg1;
        graphics = arg1.graphics;
        exprs = graphics.exprs;
        model = arg1.model;
        while (true) {
            [ok,this.dt,this.ff,exprs] = scicos_getvalue([["Set Event Delay block parameters"],["Delay  is the delay between an input event "],["       and the generated output event"],["Block may initially generate an output event before "],["       any input event. \"Date of initial output event\""],["       gives the date of this event. Set a negative value"],["       to disable any output event."]],["Delay","Date of initial output event"],list("vec",1,"vec",1),exprs);
            if (!ok) {
                break;
            }
            if (this.dt<=0) {
                message("Delay must be positive");
                ok = false;
            }
            if (ok) {
                graphics.exprs = exprs;
                model.rpar = [[this.dt],[this.ff]];
                model.firing = this.ff;
                this.x.graphics = graphics;
                this.x.model = model;
                break;
            }
        }
        return new BasicBlock(this.x);
    }
}
